package com.myfirstproject;

import com.myfirstproject.utilities.TestBase;
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;

public class Day06_Alerts extends TestBase {
    /*
    ***What is alert?
    -It is a pop-up that is generated by JS
    -Alerts are used to give informational messages
    -When there is an alert pop-up on the page, we must handle the alert otherwise we can not move on
    ***How do you handle alerts?
    -Switch to alert then use accept to click OK,
     dismiss to click Cancel,
     getText to get the text,
     and 'sendKeys' to type pn the alert
     */
    @Test
    public void acceptAlert(){

    /*
        acceptAlert() => click on the first alert,
        verify the text “I am a JS Alert” ,
        click OK ,
        and Verify “You successfully clicked an alert”
    */
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");

//    acceptAlert() => click on the first alert,
        driver.findElement(By.xpath("//button[@onclick='jsAlert()']")).click();

//    verify the text "I am a JS Alert" ,
        String actualAlertText = driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS Alert", actualAlertText);

//    click OK ,
        driver.switchTo().alert().accept();

//     and Verify "You successfully clicked an alert"
        String actualResultText = driver.findElement(By.id("result")).getText();
        Assert.assertEquals("You successfully clicked an alert", actualResultText);

    }
    @Test
    public void dismissAlert(){

    /*
        dismissAlert()=> click on the second alert,
        verify text "I am a JS Confirm”,
        click cancel,
        and Verify “You clicked: Cancel”
    */
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");

//    dismissAlert()=> click on the second alert,
        driver.findElement(By.xpath("//button[@onclick='jsConfirm()']")).click();

//    verify text "I am a JS Confirm",
        String actualAlertText = driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS Confirm", actualAlertText);

//     click cancel,
        driver.switchTo().alert().dismiss();

        //and Verify "You clicked: Cancel"
        String actualResultText = driver.findElement(By.xpath("//p[@id='result']")).getText();
        Assert.assertEquals("You clicked: Cancel", actualResultText);
    }

    @Test
    public void sendKeysAlert(){

    /*
        sendKeysAlert()=> click on the third alert,
        verify text “I am a JS prompt”,
        type “Hello World”,
        click OK,
        and Verify “You entered: Hello World”
        Collapse
    */

        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");

//   click on the third alert
        driver.findElement(By.xpath("//button[@onclick='jsPrompt()']")).click();

//   verify text "I am a JS prompt
        String actualAlertText = driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS prompt",actualAlertText);

//   type "Hello World"
        driver.switchTo().alert().sendKeys("Hello World");

//   click OK
        driver.switchTo().alert().accept();

//   Verify “You entered: Hello World”
        String actualResultText = driver.findElement(By.id("result")).getText();
        Assert.assertEquals("You entered: Hello World",actualResultText);

    }
}